import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { openDb } from "../src/db.ts";
import { APPROVAL_TTL_MS, createAuthorization } from "../src/deliveryAuthorization.ts";
import { ensureLayout, loadLayout } from "../src/layout.ts";
import { saveExplicitDeliveryTarget } from "../src/taskDeliveryTarget.ts";
import { projectTaskProgress } from "../src/taskProgress.ts";
import { recordTaskPrMerged, recordTaskPrOpened } from "../src/taskPrReceipt.ts";
import { createTask, updateTaskState } from "../src/tasks.ts";
const STALL=15*60_000; let ws:string; let ctrl:string; let savedWs:string|undefined; let savedCtrl:string|undefined;
beforeEach(()=>{savedWs=process.env.GRANDE_WORKSPACE;savedCtrl=process.env.GRANDE_CONTROL;ws=mkdtempSync(join(tmpdir(),"inactive-ws-"));ctrl=mkdtempSync(join(tmpdir(),"inactive-ctrl-"));process.env.GRANDE_WORKSPACE=ws;process.env.GRANDE_CONTROL=ctrl;ensureLayout(loadLayout())});
afterEach(()=>{if(savedWs===undefined)delete process.env.GRANDE_WORKSPACE;else process.env.GRANDE_WORKSPACE=savedWs;if(savedCtrl===undefined)delete process.env.GRANDE_CONTROL;else process.env.GRANDE_CONTROL=savedCtrl;rmSync(ws,{recursive:true,force:true});rmSync(ctrl,{recursive:true,force:true})});
function makeTask(db:ReturnType<typeof openDb>){return createTask(db,{taskId:"task-inactive",repoId:"demo",branch:"grande/inactive-1",baseCommit:"base",worktreePath:join(ws,"fake-worktree"),state:"READY"})}
function options(t:ReturnType<typeof makeTask>,extra:Record<string,unknown>={}){return{readHead:()=>"1".repeat(40),filesChanged:()=>1,workingTreeDirty:()=>false,deployConfigured:()=>false,worktreeExists:()=>true,now:()=>t.updatedAt+10*STALL,stallAfterMs:STALL,...extra}}
function addAttestation(db:ReturnType<typeof openDb>,commit="1".repeat(40)){db.prepare(`INSERT INTO job (jobId,taskId,profile,argv,state,pgid,exitCode,startedAt,endedAt,artifactPath,summary,workspaceDigest,hostToolchain) VALUES ('job-pass','task-inactive','typecheck','[]','passed',NULL,0,1,2,NULL,NULL,'digest',?)`).run(JSON.stringify({node:"v24",pnpm:"10",lockfileSha256:"abc"}));db.prepare(`INSERT INTO attestation (attestationId,taskId,"commit",profile,jobId,exitCode,startedAt,endedAt,hostToolchain) VALUES ('att-pass','task-inactive',?,'typecheck','job-pass',0,1,2,?)`).run(commit,JSON.stringify({node:"v24",pnpm:"10",lockfileSha256:"abc"}))}
function addPr(db:ReturnType<typeof openDb>,merged=false){const input={taskId:"task-inactive",prNumber:4,prUrl:"https://github.com/example/demo/pull/4",headSha:"1".repeat(40),baseRef:"main",baseSha:"2".repeat(40)};recordTaskPrOpened(db,input);if(merged)recordTaskPrMerged(db,{...input,mergeSha:"3".repeat(40)})}
function addAuthorization(db:ReturnType<typeof openDb>,status:"READY"|"APPROVED"|"UNCERTAIN"){const createdAt=Date.now();const auth=createAuthorization(db,{kind:"delivery",taskId:"task-inactive",binding:{authorizationKind:"delivery",taskId:"task-inactive",repoId:"demo",worktreeRealpath:join(ws,"fake-worktree"),deliveryTarget:"deploy",deployTarget:"prod",deploySpecDigest:`sha256:${"1".repeat(64)}`,policyDigest:`sha256:${"2".repeat(64)}`,runtimeBuild:"build",toolsetEpoch:1,toolsDigest:`sha256:${"3".repeat(64)}`,createdAt,expiresAt:createdAt+APPROVAL_TTL_MS,prNumber:4,baseRef:"main",baseSha:"2".repeat(40),headSha:"1".repeat(40),mergeMethod:"merge",expectedMergeTree:"4".repeat(40),deployRef:"profile:deploy",verifyRef:"profile:verify"},stages:{},now:createdAt});db.prepare("UPDATE delivery_authorization SET status=? WHERE authorizationId=?").run(status,auth.authorizationId)}
describe("Task 4 inactive lifecycle projection",()=>{
it("classifies an aged local agent step as stalled_agent",()=>{const db=openDb(loadLayout());const t=makeTask(db);const p=projectTaskProgress(db,t,options(t));expect(p.liveness.classification).toBe("stalled_agent");expect(p.liveness.state).toBe("stalled");expect(p.cleanupEligibility!.eligible).toBe(false);db.close()});
it("classifies an aged delivery approval as waiting_human",()=>{const db=openDb(loadLayout());const t=makeTask(db);saveExplicitDeliveryTarget(db,t.taskId,"deploy");addAuthorization(db,"READY");const p=projectTaskProgress(db,t,options(t));expect(p.liveness.classification).toBe("waiting_human");expect(p.cleanupEligibility!.eligible).toBe(false);db.close()});
it("classifies an aged opened PR with unknown live CI as waiting_ci",()=>{const db=openDb(loadLayout());const t=makeTask(db);addAttestation(db);addPr(db);const p=projectTaskProgress(db,t,options(t));expect(p.phase).toBe("ci");expect(p.liveness.classification).toBe("waiting_ci");expect(p.cleanupEligibility!.eligible).toBe(false);db.close()});
it("classifies an aged external merge/reconciliation boundary as waiting_external",()=>{const db=openDb(loadLayout());const t=makeTask(db);addAttestation(db);addPr(db,true);const p=projectTaskProgress(db,t,options(t));expect(p.cleanupRequired).toBe(true);expect(p.liveness.classification).toBe("waiting_external");expect(p.cleanupEligibility!.eligible).toBe(true);db.close()});
it("dirty or uncertain delivery remains fail-closed for cleanup",()=>{const db=openDb(loadLayout());const t=makeTask(db);addAttestation(db);addPr(db,true);const dirty=projectTaskProgress(db,t,options(t,{workingTreeDirty:()=>true}));expect(dirty.cleanupEligibility).toMatchObject({eligible:false});saveExplicitDeliveryTarget(db,t.taskId,"deploy");addAuthorization(db,"UNCERTAIN");const uncertain=projectTaskProgress(db,t,options(t));expect(uncertain.cleanupEligibility).toMatchObject({eligible:false});db.close()});
it("completed CLOSED task with removed worktree is archived without false code/test blockers",()=>{const db=openDb(loadLayout());const t=makeTask(db);addPr(db,true);updateTaskState(db,t.taskId,"CLOSED",t.stateVersion);const closed={...t,state:"CLOSED" as const,stateVersion:t.stateVersion+1};const p=projectTaskProgress(db,closed,options(closed,{readHead:()=>{throw new Error("removed")},filesChanged:()=>{throw new Error("removed")},workingTreeDirty:()=>{throw new Error("removed")},worktreeExists:()=>false}));expect(p.completed).toBe(true);expect(p.phase).toBe("completed");expect(p.blocker).toBeNull();expect(p.stages.code.state).not.toBe("blocked");expect(p.stages.tests.state).not.toBe("blocked");expect(p.cleanupEligibility!.eligible).toBe(false);db.close()})});
